### ISSUE TITLE
Make Category > Name as text field

### ISSUE THREAD

**Issue by jmencisom** [encisosystems/carpa#10]
Please make Category > Name  a text field, e.g., I would like to be able to type:

"maturity:green"
"maturity:mature"
"maturity: overmature"
"maturity:rotten"
"maturity:cob"
"maturity:other"

Thank you.

**Comment by danialeresbar** [comment]
Done!

I've made a [commit](https://github.com/encisosystems/carpa/blob/develop/harvests/models.py) in develop branch for solving this! 😃
