### ISSUE TITLE
Register to confenrece

### ISSUE THREAD

**Issue by jmencisom** [encisosystems/carpa#120]
Please register at: 
https://docs.google.com/forms/d/e/1FAIpQLSc9K2k0P8JnWlsL8nhedv1rqfwuj-Ysa9uSmocUuOzq-4h5lw/viewform?gxids=7628

![unnamed](https://user-images.githubusercontent.com/1332546/109074080-413bb900-76c5-11eb-9744-c177cfeb7c12.png)

Then ask you colleagues to do so.

**Comment by rocandres** [comment]
task completed and registration completed.

![image](https://user-images.githubusercontent.com/78989283/109093677-c08db480-76e6-11eb-815b-9e5a8cd2e67d.png)
