### ISSUE TITLE
Problem with push my branch

### ISSUE THREAD

**Issue by carmagedon07** [encisosystems/carpa#139]
Greetings

When I try to push my branch in the repository remote , I can not get it, the system show me this messenge.

![image](https://user-images.githubusercontent.com/36909609/109313357-1dd45380-7816-11eb-87fc-19500dba2239.png)

Could help me?

**Comment by danialeresbar** [comment]
If your branch has the objective of uploading the Origin model, I have previously notified the person in charge of this task #9 that it has already been solved.
When you create a branch to make changes in development branch, follow these steps:

- Update all branches of your local repository based on the branches of this repository (usually 'origin'):
```
git pull origin <outdated-branch>
```
- Create the new branch from the develop branch and move to it:
```
git checkout -b <branch-name>
```
>You should make sure you are on the develop branch: *git checkout develop*
- Make the necessary changes and their respective commits. Once you have your work ready you can upload your branch remotely to later create the **Pull Request**:
```
git push origin <branch-name>
```
- Finally, you must create the **Pull Request** from the repository requesting to integrate the changes to the branch where you created your changes. In this case, it would be the develop branch. You assign me as a reviewer and let's hope everything goes well

**Comment by diferpaho** [comment]
In the case that the branch was created locally but still does not exist in the repository in github, you can write: `git push`
and the console shows the suggestion of the command that should be used to upload the new branch.

**Comment by carmagedon07** [comment]
thanks for you help, I have been able to do  "the pull request".
