### ISSUE TITLE
Add creation date filter feature to the django admin for the harvests application models

### ISSUE THREAD

**Issue by danialeresbar** [encisosystems/carpa#14]
![Filter](https://user-images.githubusercontent.com/36459449/107983821-945e8f00-6f94-11eb-9081-52ddd749b922.PNG)

**Comment by rocandres** [comment]
issue assigned to @NicolasBorda96

**Comment by NicolasBorda96** [comment]
![image](https://user-images.githubusercontent.com/68128430/108467349-1085fa80-7253-11eb-92ce-91b66979b037.png)
I don't know why, the interface is different.
![image](https://user-images.githubusercontent.com/68128430/108467375-1976cc00-7253-11eb-8112-38d003382013.png)
![image](https://user-images.githubusercontent.com/68128430/108467388-1e3b8000-7253-11eb-9ccd-7531552ba66a.png)
A filter was created for the harvest creation date, task done.

**Comment by danialeresbar** [comment]
Once you have tried everything locally you must open a **PR** requesting to integrate the branch you worked with to the **develop** branch. In the **PR** you must add **me** for review and once it is integrated you can close this issue
