### ISSUE TITLE
Replace image in login

### ISSUE THREAD

**Issue by jmencisom** [encisosystems/carpa#140]
In this page https://carpa.encisosystems.com/, please replace the "Carpa in Action" image by the Spanish one. Thanks!

![carpa-en-accion](https://user-images.githubusercontent.com/1332546/109350261-33ad3d00-7845-11eb-8e89-e2b90741591a.png)

**Comment by jmencisom** [comment]
@rocandres pls assign to the right person

**Comment by rocandres** [comment]
Good morning,
task assigned to @carmagedon07 

Any concerns add a comment.
