### ISSUE TITLE
Test for the ParcelOwner model

### ISSUE THREAD

**Issue by danialeresbar** [encisosystems/carpa#147]
- [x] Create the respective **test_models.py** file of the **sources** application folder
- [x] You can create the objects you need for your fixtures in your local and then save them in json format with:
Please check [this](https://docs.djangoproject.com/en/3.1/ref/django-admin/)
```
docker exec -it carpa manage.py dumpdata <appname.model> --indent 4 --format json > <fixture-name>.json
```
> You may need to change the permissions or the owner of the created fixture:
> *sudo chown username:usergroup filepath* 
- [x] Write the CRUD tests. A tagged method or function for each test following the best practices.
- [x] Check the syntax and assertion of your tests
- [x] Run tests with:
```
make testtag tag=<test-tag> 
```
- [x] If everything went well, you can open a pull request

**Comment by rocandres** [comment]
Good morning,
task assigned to @cgaray22

Any concerns add a comment.

**Comment by cgaray22** [comment]
Test is created for the parcelowner model, pull request is generated.
