### ISSUE TITLE
update view name and templete origin

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#156]
The "origin" model is replaced by "Parcel", so the related files must be updated on the front.

Steps:

- [ ] rename in `views.py`

- [ ] rename the template `origin.html`

- [ ] rename in `urls.py`

- [ ] change the `href` attribute in `harvests/templates/harvests.html`

- [ ] rename the `test_origin_GET` and configure it to work properly

**Comment by osbbarr1** [comment]
Good morning.
Kindly inform that this activity took place on 27 / Feb / 2021 in the afternoon.
thank you very much :)

**Comment by diferpaho** [comment]
the changes were never approved because I did not make them correctly, please update your `release/front-end ` branch and make the changes.

**Comment by diferpaho** [comment]
You closed a pull request and it was never approved, the pull requests should only be closed by the person in charge of the review, I will open the pull reequest again and accept it, then close this task again.

**Comment by diferpaho** [comment]
It gives me problems to approve a closed pull request, please create the pull request with return to the changes to be able to approve it.

**Comment by osbbarr1** [comment]
good afternoon
kindly inform that task 156 was resolved with pullrequest #191 
Thank you
