### ISSUE TITLE
Create interface test for harvests

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#157]
Create the respective interface test for the harvests.html template.

you can use the test for test_vehicles_GET as a guide.

- [x] add a screenshot of the test results

**Comment by rocandres** [comment]
Good morning,
task assigned to @CateValencia 

Any concerns add a comment.

**Comment by CateValencia** [comment]
Hello!!!

Task DONE

![image](https://user-images.githubusercontent.com/68095616/110066761-3aa1e700-7d40-11eb-849a-2782e7d70dcf.png)

![image](https://user-images.githubusercontent.com/68095616/110066806-50171100-7d40-11eb-863a-296037fc4d7e.png)

**Comment by diferpaho** [comment]
Excellent!
