### ISSUE TITLE
Create interface test for home

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#158]
Create the respective interface test for the home.html template.

you can use the test for test_vehicles_GET as a guide.

- [ ] add a screenshot of the test results

**Comment by rocandres** [comment]
Good morning,
task assigned to @mauriciomosqueragutierrez 

Any concerns add a comment.

**Comment by mauriciomosqueragutierrez** [comment]
Good night Team.
Task done.
Thanks.

**Comment by mauriciomosqueragutierrez** [comment]
![image](https://user-images.githubusercontent.com/78989342/110068438-b05b8200-7d43-11eb-9c92-535aa466c4b8.png)
Test results screenshot added.
Thanks
Gnite!

**Comment by diferpaho** [comment]
Excellent!
