### ISSUE TITLE
Create interface test for login

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#159]
Create the respective interface test for the login.html template.

you can use the test for test_vehicles_GET as a guide.

- [ ] add a screenshot of the test results

**Comment by rocandres** [comment]
Good morning,
task assigned to @jaserranoj 

Any concerns add a comment.

**Comment by jaserranoj** [comment]
@rocandres  Hi, I was reviewing the source code related to login, and found that the login functionality is not implemented. The input user and password and the login button is associated with a link like <button type = "button" class = "button form-control btn btn-block text-white btn-user"> <a href = "/ home" class = "text -white "> Enter </a> </button>
I wanted to ask if the test interface would apply anyway. Thanks

**Comment by jaserranoj** [comment]
https://github.com/encisosystems/carpa/pull/187/commits/cb8fd2ad23420bc2dcb128aaa9320882e1b5e3ed
