### ISSUE TITLE
Create interface test for create_report

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#160]
Create the respective interface test for the create_report.html template.

you can use the test for test_vehicles_GET as a guide.

- [x] add a screenshot of the test results

**Comment by rocandres** [comment]
Good morning,
task assigned to @ElkinMoreno01226 

Any concerns add a comment.

**Comment by ElkinMoreno01226** [comment]
Done 
![image](https://user-images.githubusercontent.com/67612376/110036888-afa6f980-7d0b-11eb-8a69-714cd10695ab.png)

**Comment by diferpaho** [comment]
Excellent!
