### ISSUE TITLE
Create interface test for query_report

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#161]
Create the respective interface test for the query_report.html template.

you can use the test for test_vehicles_GET as a guide.

- [ ] add a screenshot of the test results

**Comment by rocandres** [comment]
Good morning,
task assigned to @juan5d 

Any concerns add a comment.

**Comment by juan5d** [comment]
Sorry, exist one example in the present project?

**Comment by diferpaho** [comment]
Of course in class it was explained and can be guided by `vehicle tests _GET`

**Comment by juan5d** [comment]
Thank you, please check it's ok

**Comment by diferpaho** [comment]
task completed, very good

**Comment by juan5d** [comment]
![Captura de Pantalla 2021-03-04 a la(s) 11 17 03 p  m](https://user-images.githubusercontent.com/11222298/110066813-55745b80-7d40-11eb-8fe6-e839c6ae3ddc.png)
