### ISSUE TITLE
Create interface test for reports

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#162]
Create the respective interface test for the reports.html template.

you can use the test for test_vehicles_GET as a guide.

- [ ] add a screenshot of the test results

**Comment by rocandres** [comment]
Good morning,
task assigned to @rafa2640 

Any concerns add a comment.

**Comment by rafa2640** [comment]
Hello

Current test for the reports

![image](https://user-images.githubusercontent.com/17261023/110065173-99fdf800-7d3c-11eb-87ad-f4f1d936d30f.png)

**Comment by diferpaho** [comment]
Excellent!
