### ISSUE TITLE
Create interface test for people

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#163]
Create the respective interface test for the people.html template.

you can use the test for test_vehicles_GET as a guide.

- [x] add a screenshot of the test results

**Comment by rocandres** [comment]
Good morning,
task assigned to @carmagedon07 

Any concerns add a comment.

**Comment by carmagedon07** [comment]
greeting 

it was the result.


![imagen](https://user-images.githubusercontent.com/36909609/110066188-da5e7580-7d3e-11eb-8028-1e2e5b9e3c20.png)

I can't understand, if the logic is right.

![imagen](https://user-images.githubusercontent.com/36909609/110066254-00841580-7d3f-11eb-997f-d8bb835ba8cf.png)

**Comment by carmagedon07** [comment]
sorry, this is the code in the test_view

![imagen](https://user-images.githubusercontent.com/36909609/110066304-23aec500-7d3f-11eb-969d-e14a57166550.png)

**Comment by diferpaho** [comment]
Great!

**Comment by carmagedon07** [comment]
greetings 

I have got it already.

![image](https://user-images.githubusercontent.com/36909609/110135185-34415880-7d9c-11eb-80b5-bea8efecd5c8.png)


thanks @diferpaho  for your advice.
