### ISSUE TITLE
Remove links in homepage

### ISSUE THREAD

**Issue by jmencisom** [encisosystems/carpa#170]
In this page https://carpa.encisosystems.com/, pls remove the following links:

Olvido su contraseña?

Crear una cuenta

Thanks.

**Comment by rocandres** [comment]
Good morning,
task assigned to @jaserranoj 

Any concerns add a comment.

**Comment by jaserranoj** [comment]
https://github.com/encisosystems/carpa/pull/186/commits/8ab570f096277fb8840efdaf2219c56187c0ac49
