### ISSUE TITLE
not all tests are executed

### ISSUE THREAD

**Issue by rfonseca7** [encisosystems/carpa#175]
class 

![Captura de Pantalla 2021-03-04 a la(s) 12 20 58 p  m](https://user-images.githubusercontent.com/39870129/110003125-157f8b00-7ce4-11eb-8dbe-d02021236909.png)

when running the tests, only run one

![Captura de Pantalla 2021-03-04 a la(s) 12 21 44 p  m](https://user-images.githubusercontent.com/39870129/110003255-31832c80-7ce4-11eb-8793-6d33ead476ed.png)

How do I get all the tests created to run?

**Comment by danialeresbar** [comment]
Check the Unit Test django docs
All test methods must be named with test_<your test_name>
