### ISSUE TITLE
Report Frontend tasks

### ISSUE THREAD

**Issue by jmencisom** [encisosystems/carpa#2]
Please report Frontend tasks. Each task should require small effort and be independent between each other.

**Comment by jmencisom** [comment]
Please let us know in the comments when you have a progress in this task. How many tasks you expect to report?

Thank you.

**Comment by diferpaho** [comment]
So far I have reported 3 tasks, but the idea is to add 5 more today.

**Comment by diferpaho** [comment]
The first 8 tasks were reported

**Comment by jmencisom** [comment]
Thanks and this is done, feel free to close it.

**Comment by diferpaho** [comment]
all tasks were reported and there are few to be completed.
