### ISSUE TITLE
Solve Log error: "/usr/bin/env: ‘bash\r’: No such file or directory" - Docker desktop for Windows

### ISSUE THREAD

**Issue by dcarranza9** [encisosystems/carpa#42]
I'm getting this message in log of carpa's container when I try to up it through docker desktop or using "docker-compose up" command in windows command line

**Comment by dcarranza9** [comment]
Just like this [article ] (https://www.xspdf.com/resolution/50789087.html) explains : 

"One of the issues with Docker (or any Linux/macOS based system) on Windows is the difference in how line endings are handled...the best thing is to avoid the issue by setting git config --global core.autocrlf input which makes git clone using unix endings, and converts windows endings on commit"

So I tried to use the git command  `$ git config --global core.autocrlf true`, to clone again the carpa repository and rebuild all docker images but I got same error log. 

However after a few searches I found same error in the issues log of other [github repository(https://github.com/tiangolo/uwsgi-nginx-flask-docker/issues/127)
and after to read all replies I tried to clone again carpa repository using `--config core.autocrlf=input` as parameter of git command such as 
`$ git clone https://github.com/encisosystems/carpa.git --config core.autocrlf=input` 

It works for me, the project run ok!

**Comment by danialeresbar** [comment]
You can use a WSL (could be Ubuntu) to clone the repository and run the repository on your premises. It is faster and easier than installing a virtual machine
