### ISSUE TITLE
Update cards part 1

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#44]
Update the cards in the menu of https://carpa.encisosystems.com/harvests so that the appearance is the same as the cards of the menu of https://carpa.encisosystems.com/home.

Before any changes review the guide:
https://github.com/encisosystems/carpa/wiki/Front-end

**Comment by diferpaho** [comment]
If you can't find the edit button, please add it

**Comment by rocandres** [comment]
Good morning,
task assigned to @CateValencia 

Any concerns add a comment.

**Comment by CateValencia** [comment]
Good morning!

Task DONE.
