### ISSUE TITLE
Update cards part 2

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#45]
Update the cards in the menu of https://carpa.encisosystems.com/reports so that the appearance is the same as the cards of the menu of https://carpa.encisosystems.com/home.

Before any changes review the guide:
https://github.com/encisosystems/carpa/wiki/Front-end

**Comment by rocandres** [comment]
Good morning,
task assigned to @rafa2640 

Any concerns add a comment.

**Comment by rafa2640** [comment]
Good morning

task done https://github.com/encisosystems/carpa/pull/88
:)

**Comment by diferpaho** [comment]
Excellent!
