### ISSUE TITLE
Add cards

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#47]
Add cards for bunch batch, bunch, sensor and bunch category, in the menu https://carpa.encisosystems.com/harvests.

Before any changes review the guide:
https://github.com/encisosystems/carpa/wiki/Front-end

**Comment by rocandres** [comment]
Good morning,
task assigned to @osbbarr1 

Any concerns add a comment.

**Comment by osbbarr1** [comment]
Add cards for bunch batch, bunch, sensor and bunch category

**Comment by osbbarr1** [comment]
![image](https://user-images.githubusercontent.com/5799183/109208975-fed3b400-7778-11eb-8e4d-6c2393898f1f.png)

**Comment by osbbarr1** [comment]
activity performed pull requests :)

**Comment by diferpaho** [comment]
It gives me problems to approve a closed pull request, please create the pull request with return to the changes to be able to approve it.

**Comment by osbbarr1** [comment]
Good morning Diego, please indicate in which documentation or video I can specifically validate the request. Thanks

**Comment by diferpaho** [comment]
I think you still don't understand the problem, you close the pull requests and now I can't approve them, you must recreate the pull request with the same code that was changed to be approved, don't close the pull requests or the same will make it happen again, in summary re-create the pull request.

**Comment by osbbarr1** [comment]
when I try to create the new pullrequest, it doesn't allow and I get the following message.

![image](https://user-images.githubusercontent.com/5799183/110168200-d5440980-7dc4-11eb-9708-158d8f174da4.png)

**Comment by osbbarr1** [comment]
Thank you very much, I am attentive to new indications

**Comment by osbbarr1** [comment]
I also see that the pull request is open,
please indicate which button to replicate or enable again.
Thank you very much

![image](https://user-images.githubusercontent.com/5799183/110169299-813a2480-7dc6-11eb-9711-44c0ecc41811.png)
