### ISSUE TITLE
Add icons part 1

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#50]
Change the words in the buttons of https://carpa.encisosystems.com/origin by icons, you can guide yourself from https://carpa.encisosystems.com/people, the icons should be the same.

Before any changes review the guide:
https://github.com/encisosystems/carpa/wiki/Front-end

**Comment by rocandres** [comment]
Good morning,
task assigned to @juan5d 

Any concerns add a comment.

**Comment by juan5d** [comment]
Problem with permits, my local is associated with work user
i did change global user in my machine, but not work

**Comment by diferpaho** [comment]
> Problem with permits, my local is associated with work user
> i did change global user in my machine, but not work

Can I solve the problem?

**Comment by diferpaho** [comment]
Excellent!

**Comment by diferpaho** [comment]
review pull request comments

**Comment by juan5d** [comment]
Please see and check if it's ok

**Comment by diferpaho** [comment]
The file you modify is harvests `/templates/origin.html ` but now that file has been moved to sources `/templates/origin.html`, please update your `release/front-end` branch and add the icons for the file that was moved, also add the edit button with its respective icon.

**Comment by juan5d** [comment]
Ok, it's already, please check pull request
