### ISSUE TITLE
Add icons part 2

### ISSUE THREAD

**Issue by diferpaho** [encisosystems/carpa#51]
Change the words in the buttons of https://carpa.encisosystems.com/vehicles by icons, you can guide yourself from https://carpa.encisosystems.com/people, the icons should be the same.

Before any changes review the guide:
https://github.com/encisosystems/carpa/wiki/Front-end

**Comment by diferpaho** [comment]
If you can't find the edit button, please add it

**Comment by rocandres** [comment]
Good morning,
task assigned to @ElkinMoreno01226 

Any concerns add a comment.

**Comment by jmencisom** [comment]
Any news? Please let us know how can we help
