### ISSUE TITLE
Include CARPA Logo

### ISSUE THREAD

**Issue by jmencisom** [encisosystems/carpa#52]
Feel free to generate favicon as well.

![Logo CARPA](https://user-images.githubusercontent.com/1332546/108517678-b78b8600-7295-11eb-8f51-cfa56075340d.png)

**Comment by jmencisom** [comment]
Solved, right?

**Comment by jmencisom** [comment]
Please link the related pull request. Thanks a lot!

**Comment by diferpaho** [comment]
Yes sir, it is already in charge in the pull request #115
