### ISSUE TITLE
Create the Vehicle model

### ISSUE THREAD

**Issue by danialeresbar** [encisosystems/carpa#69]
- [ ] Create the model with their respective fields and constraints (first approach) in the **models.py**
- [ ] Create the AdminModel and customize it in the **admin.py** file
- [ ] Verify the correct display of the objects and forms of the models in the **admin** panel
- [ ] Open a pull request

**Comment by rocandres** [comment]
Good morning,
task assigned to @rfonseca7 

Any concerns add a comment.

**Comment by danialeresbar** [comment]
This task has been solved!
