### ISSUE TITLE
organize groups to assign tasks

### ISSUE THREAD

**Issue by rocandres** [encisosystems/carpa#70]
Please state how the groups are made up. Define who is the backend and who is the frontend.

**Comment by CateValencia** [comment]
Good Morning

Users and role:
F4brii = BackEnd
CateValencia = FrontEnd

**Comment by rafa2640** [comment]
Good Afternoon

Users and role:
NicolasBorda96 = BackEnd
Rafa2640 = FrontEnd

**Comment by osbbarr1** [comment]
osbbarr1 = Frontend
cgaray = Backend

**Comment by juan5d** [comment]
Good evening

dcarranza9 = Backend
juan5d = Frontend

**Comment by rfonseca7** [comment]
rfonseca7 = BackEnd
ElkinMoreno01226 = FrontEnd

**Comment by mauriciomosqueragutierrez** [comment]
Users/Role:
OscarMiguelToro = BackEnd
mauriciomosqueragutierrez = FrontEnd
Gnite!

**Comment by carmagedon07** [comment]
Greetings

PCaroDi07 = frontEnd

Regrats!

**Comment by rocandres** [comment]
Task completed.
