### ISSUE TITLE
Create the Report model

### ISSUE THREAD

**Issue by danialeresbar** [encisosystems/carpa#71]
- [x] Create the model with their respective fields and constraints (first approach) in the **models.py**
- [x] Create the AdminModel and customize it in the **admin.py** file
- [x] Verify the correct display of the objects and forms of the models in the **admin** panel
- [x] Open a pull request

**Comment by rocandres** [comment]
Good morning,
task assigned to @otoro90 

Any concerns add a comment.

**Comment by rocandres** [comment]
Good evening, @otoro90  any expected resolution date ?. Task #87  depends on the completion of this task.

**Comment by rocandres** [comment]
Good evening, @otoro90 any expected resolution date ?. Task #87 depends on the completion of this task.
