### ISSUE TITLE
Create the BunchBatch model

### ISSUE THREAD

**Issue by danialeresbar** [encisosystems/carpa#74]
- [x] Create the model with their respective fields and constraints (first approach) in the **models.py**
- [x] Create the AdminModel and customize it in the **admin.py** file
- [x] Verify the correct display of the objects and forms of the models in the **admin** panel
- [x] Open a pull request

**Comment by rocandres** [comment]
Good morning,
task assigned to @cgaray22 

Any concerns add a comment.

**Comment by danialeresbar** [comment]
Task solved!
