### ISSUE TITLE
Add Space between model name

### ISSUE THREAD

**Issue by jmencisom** [encisosystems/carpa#78]
In the admin https://carpa.encisosystems.com/admin/, please add spaces between the model names:

BunchCategories --> Bunch Categories
BatchSources --> Batch Sources

Thank you.

<img width="419" alt="Captura de Pantalla 2021-02-19 a la(s) 3 42 31 p  m" src="https://user-images.githubusercontent.com/1332546/108559349-38b04080-72c9-11eb-961c-b488b6ca39ec.png">

**Comment by rocandres** [comment]
Good morning,
task assigned to @F4brii 

Any concerns add a comment.

**Comment by jmencisom** [comment]
@F4brii any expected resolution date?

**Comment by F4brii** [comment]
@jmencisom, today resolved.
