### ISSUE TITLE
Someone can help me with this mistake docker

### ISSUE THREAD

**Issue by rafa2640** [encisosystems/carpa#83]
![image](https://user-images.githubusercontent.com/17261023/108576696-8be7ba80-72ec-11eb-9896-55b3bdab3997.png)
![image](https://user-images.githubusercontent.com/17261023/108576729-a9b51f80-72ec-11eb-851c-235c4a427d66.png)

**Comment by danialeresbar** [comment]
Your **logs** are not very helpful 😥. Please show us the error with the specific **container**.
@dcarranza9 Could it be something similar to what happened to you?

**Comment by rafa2640** [comment]
![image](https://user-images.githubusercontent.com/17261023/108580916-b2612200-72fb-11eb-878f-155e7b1b6bd8.png)

**Comment by jmencisom** [comment]
#42

**Comment by jmencisom** [comment]
Is this solved?

**Comment by jmencisom** [comment]
@rafa2640: did #42 work?
