### ISSUE TITLE
Error starting CARPA project

### ISSUE THREAD

**Issue by NicolasBorda96** [encisosystems/carpa#86]
Download the repository again with the help of git extension and start the docker, which only goes so far.
![image](https://user-images.githubusercontent.com/68128430/108598807-e5d49880-735d-11eb-84b1-41d9bf519d44.png)
And if I run the runserver command, it throws the following error.
![image](https://user-images.githubusercontent.com/68128430/108598773-9aba8580-735d-11eb-822d-4cdc5b7b92e6.png)
I appreciate your help.

**Comment by NicolasBorda96** [comment]
Solution: #42

**Comment by danialeresbar** [comment]
Please try to perform the steps mentioned in the **README**.
Down the containers and then do a **build** 😁
