### ISSUE TITLE
Add creation date filter feature to the Django admin for the reports application models

### ISSUE THREAD

**Issue by danialeresbar** [encisosystems/carpa#87]

**Comment by rocandres** [comment]
The task could not be completed, because task #71  has not been closed.

**Comment by danialeresbar** [comment]
@rocandres Take the initiative and solve both. After all, it shouldn't take you more than 1 hour and you have files that you can guide yourself from 😎
Thanks

**Comment by jmencisom** [comment]
Any news? I see  #71 closed :)

**Comment by rocandres** [comment]
task performed in pull request #138 .
