### ISSUE TITLE
Push error

### ISSUE THREAD

**Issue by CateValencia** [encisosystems/carpa#96]
once the "cards" update task was completed on my local, I made a successful "commit", but when I did "push" I got credentials error

![image](https://user-images.githubusercontent.com/68095616/108611799-34128780-73b0-11eb-8172-0809b36bea63.png)

**Comment by danialeresbar** [comment]
You should push from the respective branch (in this case fix/update...). Also, you should make sure to integrate git with VSCode correctly. Please verify this 😀

**Comment by CateValencia** [comment]
the position of the branch was correct. I entered this forum "https://stackoverflow.com/questions/62697845/git-push-origin-master-missing-or-invalid-credentials" and did the credentials configuration again in the vsc terminal.  It worked! very thanks 😀

**Comment by CateValencia** [comment]
DONE

**Comment by diferpaho** [comment]
Excellent!
